In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import re

In [3]:
Sent=pd.read_csv(r"E:\movie_review.csv", sep="\t")
Sent.head()

,id,review,sentiment
0,5814_8,With all this stuff going down at the moment w...,1
1,2381_9,"\The Classic War of the Worlds\"" by Timothy Hi...",1
2,7759_3,The film starts with a manager (Nicholas Bell)...,0
3,3630_4,It must be assumed that those who praised this...,0
4,9495_8,Superbly trashy and wondrously unpretentious 8...,1


In [4]:
Sent.shape

(22500, 3)

In [5]:
Sent["sentiment"].value_counts()

sentiment
1    11278
0    11222
Name: count, dtype: int64

In [6]:
def preprocessor(text):
    text=re.sub("<[^>]*>",'',text)
    text=(re.sub("[\W]+", ' ' , text.lower()))

    return text

In [7]:
from nltk.stem import PorterStemmer

porter=PorterStemmer()

def tokenizer_porter(text):
    token=[]
    for word in text.split():
        token.append(porter.stem(word))

    return token    

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import text 
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk

In [9]:
X=Sent["review"]
Y=Sent["sentiment"]

stopwords=[]

stop=list(text.ENGLISH_STOP_WORDS.union(stopwords))

tfidf = TfidfVectorizer(stop_words=stop,
                      tokenizer=tokenizer_porter,
                      preprocessor=preprocessor)

X_tfidf = tfidf.fit_transform(X)

X_train, X_test, Y_train, Y_test= train_test_split(X_tfidf ,Y, test_size=0.7, random_state=50)

In [10]:
X_train

<6750x50476 sparse matrix of type '<class 'numpy.float64'>'
	with 624458 stored elements in Compressed Sparse Row format>

In [11]:
# TRAINING THE MODEL

# LOGISTIC REGRESSION

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

log= LogisticRegression()
log.fit(X_train, Y_train)

predict=log.predict(X_test)

In [12]:
#ACCURACY SCORE

accuracy_score(Y_test, predict)

0.8712380952380953

In [13]:
# CONFUSION MATRIX

confusion_matrix(Y_test, predict)

array([[6658, 1202],
       [ 826, 7064]], dtype=int64)

In [14]:
# CLASSIFICATION

print("\n", classification_report( Y_test, predict))


               precision    recall  f1-score   support

           0       0.89      0.85      0.87      7860
           1       0.85      0.90      0.87      7890

    accuracy                           0.87     15750
   macro avg       0.87      0.87      0.87     15750
weighted avg       0.87      0.87      0.87     15750



In [15]:
# DECISION TREE

from sklearn.tree import DecisionTreeClassifier

dtree= DecisionTreeClassifier()
dtree.fit(X_train, Y_train)

dpredict=dtree.predict(X_test)

In [16]:
#ACCURACY SCORE

accuracy_score(Y_test, dpredict)

0.7022222222222222

In [17]:
# CONFUSION MATRIX

confusion_matrix(Y_test, dpredict)

array([[5461, 2399],
       [2291, 5599]], dtype=int64)

In [18]:
# CLASSIFICATION

print("\n", classification_report( Y_test, dpredict))


               precision    recall  f1-score   support

           0       0.70      0.69      0.70      7860
           1       0.70      0.71      0.70      7890

    accuracy                           0.70     15750
   macro avg       0.70      0.70      0.70     15750
weighted avg       0.70      0.70      0.70     15750



In [19]:
# RANDOM FOREST

from sklearn.ensemble import RandomForestClassifier

rforest=RandomForestClassifier()
rforest.fit(X_train, Y_train)

rpredict=rforest.predict(X_test)

In [20]:
#ACCURACY SCORE

accuracy_score(Y_test, rpredict)

0.8339682539682539

In [21]:
# CONFUSION MATRIX

confusion_matrix(Y_test, rpredict)

array([[6539, 1321],
       [1294, 6596]], dtype=int64)

In [22]:
# CLASSIFICATION

print("\n", classification_report( Y_test, rpredict))


               precision    recall  f1-score   support

           0       0.83      0.83      0.83      7860
           1       0.83      0.84      0.83      7890

    accuracy                           0.83     15750
   macro avg       0.83      0.83      0.83     15750
weighted avg       0.83      0.83      0.83     15750



In [23]:
# GAUSSIAN NAIVE BAYES

from sklearn.naive_bayes import GaussianNB, MultinomialNB

# MULTINOMIAL NAIVE BAYES 

mnb=MultinomialNB()
mnb.fit(X_train, Y_train)

mnbpredict = mnb.predict(X_test)


In [24]:
#ACCURACY SCORE

accuracy_score(Y_test, mnbpredict)

0.854031746031746

In [25]:
# CONFUSION MATRIX

confusion_matrix(Y_test, mnbpredict)

array([[6876,  984],
       [1315, 6575]], dtype=int64)

In [26]:
# CLASSIFICATION

print("\n", classification_report( Y_test, mnbpredict))


               precision    recall  f1-score   support

           0       0.84      0.87      0.86      7860
           1       0.87      0.83      0.85      7890

    accuracy                           0.85     15750
   macro avg       0.85      0.85      0.85     15750
weighted avg       0.85      0.85      0.85     15750



In [27]:
# K-NEAREST NEIGHBORS

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score


In [ ]:
verror =[]
neighbours=range(1,500,10)

for i in neighbours:
    knn=KNeighborsClassifier(n_neighbors=i)

    error=1-cross_val_score(knn, X_train, Y_train, cv=10).mean()
    verror.append(error)

In [ ]:
kresult=neighbours[verror.index(min(verror))]
kresult

In [ ]:
knn1=KNeighborsClassifier(n_neighbors=kresult)
knn1.fit(X_train, Y_train)

kpredict=knn1.predict(X_test)

In [ ]:
#ACCURACY SCORE

accuracy_score(Y_test, kpredict)

In [ ]:
# CONFUSION MATRIX

confusion_matrix(Y_test, kpredict)

In [ ]:
# CLASSIFICATION

print("\n", classification_report( Y_test, kpredict))

In [ ]:
# SUPPORT VECTOR MACHINE

from sklearn.svm import SVC

sverror = []
svrange =  range(1,10,10)

for i in svrange:
    
    svm = SVC(C=i, kernel='linear')
    
    error = 1 - cross_val_score(svm, X_train, Y_train,cv=5).mean()
    sverror.append(error)

In [ ]:
svmerror= svrange[sverror.index(min(sverror))]
svmerror

In [ ]:
svm1=SVC(kernel="linear", C=1).fit(X_train, Y_train)

svm1.fit(X_train, Y_train)

svmpredict=svm1.predict(X_test)

In [ ]:
#ACCURACY SCORE

accuracy_score(Y_test, svmpredict)

In [ ]:
# CONFUSION MATRIX

confusion_matrix(Y_test, svmpredict)

In [ ]:
# CLASSIFICATION

print("\n", classification_report( Y_test, svmpredict))

In [ ]:
# CONCLUSION OF ALL MODELS
